# Configuration for Embabel to use Ollama local models.
#
# Install Ollama from https://ollama.com/
# Install the required LLMs onto Ollama:
#
#     ollama run gpt-oss

# An excellent general-use model.  How to install:
#
# ollama run gpt-oss:20b
#
embabel:
  models:
    default-llm: "gpt-oss:20b"
    llms:
      best: "gpt-oss:20b"
      cheapest: "gpt-oss:20b"

# A small model to compare with gpt-oss:20b.  How to install:
#
# ollama run qwen3:4b
#
# embabel:
#   models:
#     default-llm: "qwen3:4b"
#     llms:
#       best: "qwen3:4b"
#       cheapest: "qwen3:4b"
